[package]
name = "Rust_Module"
version = "0.1.0"
authors = ["kinofmat <mat20014@byui.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
